In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.io
import math
import sklearn
import sklearn.datasets

In [2]:
np.random.seed(1)
x=np.random.randn(2, 6)
print("x = " + str(x))

x = [[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794 -2.06014071]]


In [42]:
xx = x[:, (0*2):(0+1)*2]
print(xx)

[[ 1.62434536 -0.61175641]
 [ 1.74481176 -0.7612069 ]]


In [43]:
xx = x[:, (1*2):(1+1)*2]
print(xx)

[[-0.52817175 -1.07296862]
 [ 0.3190391  -0.24937038]]


In [44]:
xx = x[:, (2*2):(2+1)*2]
print(xx)

[[ 0.86540763 -2.3015387 ]
 [ 1.46210794 -2.06014071]]


In [59]:
np.random.seed(4)
permutation = list(np.random.permutation(3))
shuffled_X = x[:, permutation]
print(shuffled_X)

[[-0.61175641  1.62434536 -0.52817175]
 [-0.7612069   1.74481176  0.3190391 ]]


In [60]:
print(permutation)

[1, 0, 2]


In [61]:
np.power(4, 2)

16

In [62]:
np.sqrt(4)

2.0

In [64]:
x[0,1]

-0.6117564136500754

In [65]:
y=np.random.randn(3, 3, 3, 5)
print("y = " + str(y))

y = [[[[ 0.45036151  0.04500167  0.9934697   1.07932256  1.45162561]
   [-0.33881198  0.36623181 -0.30501214 -0.48492332 -0.12066567]
   [-0.0788265   0.56373477 -0.18040236  0.20218012  0.16951775]]

  [[-0.71522547  0.52533388 -0.74738768  0.74981904 -2.4598148 ]
   [ 0.03600369  0.72612944  1.43327736  2.6547994  -1.21166587]
   [ 1.69268959 -1.14031579  1.65688784  1.31929701  0.61136545]]

  [[-0.441491   -1.13908785  1.98495133  0.02693565  0.35880669]
   [-1.61454139  0.82448138  0.26043704  1.37718202 -1.37307059]
   [-0.00993354 -1.38947805  1.22956251 -0.25388263  0.85576984]]]


 [[[-0.17599712 -1.69610226 -0.95617171  1.15563935  0.24133141]
   [ 0.27677085  1.04420738  0.18173901 -0.77604419  0.82242392]
   [-0.90004667  0.0362415   0.97073319 -0.65066811  0.15493329]]

  [[-1.0765125   0.11634145 -1.55579813  1.3072029   0.32773476]
   [-0.69489149  2.71679361  0.55569945 -0.04361956  1.2226314 ]
   [ 0.04559882  1.38058694  0.21525806  0.55026835 -0.38327751]]

  [[-0.99

In [67]:
print("y = " + str(y[..., 0]))

y = [[[ 0.45036151 -0.33881198 -0.0788265 ]
  [-0.71522547  0.03600369  1.69268959]
  [-0.441491   -1.61454139 -0.00993354]]

 [[-0.17599712  0.27677085 -0.90004667]
  [-1.0765125  -0.69489149  0.04559882]
  [-0.99400708  1.58509564 -1.75784563]]

 [[-0.48592231 -0.49442359  0.77821729]
  [ 2.07686269 -0.70173425  0.36347693]
  [ 0.402877    1.27911558  0.46020847]]]


In [66]:
b = np.random.randn(1,1,1,5)
print("b = " + str(b))

b = [[[[ 0.12781184 -0.42330897 -0.5292739  -1.19528179 -0.82327108]]]]


In [72]:
box1 = (2, 1, 4, 3)
box2 = (1, 2, 3, 4) 
print(box1[0])

2


In [75]:
np.random.seed(0)
p = np.array([0.1, 0.7, 0.0, 0.2])
index = np.random.choice([0, 1, 2, 3], p = p.ravel())

In [76]:
index

1

In [77]:
string = ' xoxo love xoxo   '

# Leading whitepsace are removed
print(string.strip())

xoxo love xoxo
